export const FILTER_ALL = "FILTER_ALL";
export const FILTER_NONE = "FILTER_NONE";
export const FILTER_NON_STOP = "FILTER_NON_STOP";
export const FILTER_ONE_PLANE_CHANGE = "FILTER_ONE_PLANE_CHANGE";
export const FILTER_TWO_PLANE_CHANGES = "FILTER_TWO_PLANE_CHANGES";
export const FILTER_THREE_PLANE_CHANGES = "FILTER_THREE_PLANE_CHANGES";
export const GET_FILTERED_TICKETS = "GET_FILTERED_TICKETS";
export const CLEAR_FILTERED_TICKETS = "CLEAR_FILTERED_TICKETS";
